name: CI Build

on:
  push:
    branches:
    tags:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: test
        run: go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
        working-directory: src

      - name: install golangci-lint
        run:  curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.31.0
        working-directory: src

      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run
        working-directory: src

      - name: build image
        run:  docker build --build-arg SKIP_TEST=true --build-arg CI=github .
